service: everydayparks

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 120

functions:
  sendRandomPark:
    handler: handler.sendRandomPark
    events:
      - schedule: cron(30 * * * ? *)
    maximumRetryAttempts: 0
  sendRandomNationalPark:
    handler: handler.sendRandomNationalPark
    events:
      - schedule: cron(0 17 ? * SUN *)
    maximumRetryAttempts: 0
  sendRandomNationalForest:
    handler: handler.sendRandomNationalForest
    events:
      - schedule: cron(0 17 ? * MON *)
    maximumRetryAttempts: 0
  sendRandomNationalMonument:
    handler: handler.sendRandomNationalMonument
    events:
      - schedule: cron(0 17 ? * TUE *)
    maximumRetryAttempts: 0
  sendRandomProtectedArea:
    handler: handler.sendRandomProtectedArea
    events:
      - schedule: cron(0 17 ? * THU *)
    maximumRetryAttempts: 0
  sendRandomStatePark:
    handler: handler.sendRandomStatePark
    events:
      - schedule: cron(0 16 * * ? *)
    maximumRetryAttempts: 0
  sendRandomHistoricLandmark:
    handler: handler.sendRandomHistoricLandmark
    events:
      - schedule: cron(0 18 * * ? *)
    maximumRetryAttempts: 0
